config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # change default /user/action URLs for devise
  devise_for :users, path: '', path_names: { sign_in: 'signin', sign_out: 'signout', password: 'iforgot', confirmation: 'verification', unlock: 'unlock', registration: '', sign_up: 'signup' }

  # match on /page instead of the technically correct /pages/page
  # get 'pages/welcome'
  # get 'pages/about'
  match '/about', to: 'pages#about', via: 'get'
  match '/welcome', to: 'pages#welcome', via: 'get'

  # for the temporary resource
  resources :posts

  # fall through to root
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :validatable,
         :confirmable,
         :lockable,
         :timeoutable,
         :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # override the devise signin and signout url behavior
  def after_sign_in_path_for(_resource_or_scope)
    welcome_url
  end

  def after_sign_out_path_for(_resource_or_scope)
    root_url
  end

  protected

  # Allow extra attributes for user signup and user profile edit
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:firstname, :lastname, :email, :password, :current_password, :isadmin)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:firstname, :lastname, :email, :password, :password_confirmation,
               :current_password, :isadmin)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :authenticate_user!, except: %i[index about]

  def index
  end

  def welcome
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :published)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def appname
    @appname = Rails.application.appname
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><% if content_for?(:page_title) %><%= appname %> | <%= yield(:page_title) %><% else %><%= appname %><% end %></title>
    <% if content_for?(:page_description) %><meta name="description" content="<%= yield(:page_description) %>"/><% end %>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="font-sans font-normal leading-normal text-truegray-800 bg-truegray-100 antialiased">
    <header class="sticky top-0 w-full mb-4">
      <nav class="flex flex-wrap items-center justify-between p-4 bg-cyan-800">
        <div class="lg:order-1 w-auto lg:w-1/5 lg:text-center">
          <%= link_to appname, root_path, class: "text-xl font-semibold font-heading text-gray-300 hover:text-gray-400" %>
        </div>
        <div class="block lg:hidden">
          <button class="navbar-burger flex items-right py-2 px-3 rounded border text-gray-300 hover:text-gray-400"><svg class="fill-current h-3 w-3" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path></svg></button>
        </div>
        <div class="navbar-menu hidden lg:order-1 lg:block w-full lg:w-2/5">
          <% if user_signed_in? %><%= link_to 'welcome', welcome_path, class: "block lg:inline-block px-2 mt-4 lg:mt-0 mr-10 text-gray-300 hover:text-gray-400 hover:bg-gray-200" %><% end %>
          <%= link_to "about", about_path, class: "block lg:inline-block px-2 mt-4 lg:mt-0 mr-10 text-gray-300 hover:text-gray-400 hover:bg-gray-200" %>
        </div>
        <div class="navbar-menu hidden lg:order-3 lg:block w-full lg:w-2/5 lg:text-right">
          <% if user_signed_in? %>
            <%= link_to 'edit profile', edit_user_registration_path, class: "block lg:inline-block px-2 lg:mt-0 mt-4 mr-10 text-gray-300 hover:text-gray-400 hover:bg-gray-200" %>
            <% if user_signed_in? && current_user.isadmin? %><%= link_to 'admin', rails_admin_path, class: "block lg:inline-block px-2 lg:mt-0 mt-4 mr-10 text-gray-300 hover:text-gray-400 hover:bg-gray-200" %><% end %>
            <%= link_to 'sign out', destroy_user_session_path, method: 'delete', class: "block lg:inline-block px-2 lg:mt-0 mt-4 mr-10 text-gray-300 hover:text-gray-400 hover:bg-gray-200" %><% else %>
            <%= link_to 'sign up', new_user_registration_path, class: "block lg:inline-block px-2 lg:mt-0 mt-4 mr-10 text-gray-300 hover:text-gray-400 hover:bg-gray-200" %>
            <%= link_to 'sign in', new_user_session_path, class: "block lg:inline-block px-2 lg:mt-0 mt-4 mr-10 text-gray-300 hover:text-gray-400 hover:bg-gray-200" %>
          <% end %>
        </div>
      </nav>
    </header>
    <div class="container mx-auto px-4 pt-4">
      <main class="px-4 lg:px-10">
        <% flash.each do |type, message| %>
          <% if type == "alert" %>
            <div class="bg-red-500 rounded">
              <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
            </div>
          <% end %>
          <% if type == "notice" %>
            <div class="bg-green-500 rounded">
              <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
            </div>
          <% end %>
        <% end %>
        <%= yield %>
      </main>

    </div>
    <footer class="flex flex-wrap items-center justify-between mt-6 p-4 bg-gray-400">
      <div class="flex m-auto justify-center space-x-6 mt-1 mb-1">
        <span class="text-gray-200">&copy; 2021 <%= appname %></span>
        <a href="#" class="ml-4">
          <svg class="text-cyan-600 w-6 h-6" fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
          </svg>
        </a>
        <a href="#">
          <svg class="text-cyan-600 w-6 h-6" fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z"></path>
          </svg>
        </a>
      </div>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<%= content_for :page_title, 'About Page' %>
<%= content_for :page_description, 'About Page' %>
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<section class="py-12 px-4 text-center">
  <div class="w-full max-w-2xl mx-auto">
    <span class="text-sm font-semibold">TAGLINE</span>
    <h2 class="text-5xl mt-2 mb-6 leading-tight font-semibold font-heading">Lorem ipsum dolor sit amet</h2>
    <a class="text-cyan-600 hover:underline" href="#">Learn more &raquo;</a>
  </div>
</section>
<section class="py-8 px-4">
  <div class="flex flex-wrap -mx-2">
    <div class="lg:w-2/5 px-2 lg:pr-16 mb-6 lg:mb-0">
      <h2 class="text-3xl font-semibold">Lorem ipsum dolor sit amet</h2>
    </div>
    <div class="lg:w-3/5 px-2">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
  </div>
</section>
<section class="py-12 px-4 text-center">
  <div class="w-full max-w-2xl mx-auto">
    <h2 class="text-5xl leading-tight font-semibold font-heading">Lorem ipsum dolor sit amet</h2>
    <p class="mt-6 mb-8 text-gray-400 leading-relaxed">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
    <a class="inline-block py-4 px-8 leading-none text-white bg-cyan-600 hover:bg-cyan-700 font-semibold rounded shadow" href="#">Sign up</a>
  </div>
</section>
<section class="py-8 px-4">
  <div class="flex flex-wrap -mx-4 -mb-6">
    <div class="lg:w-1/3 px-4 mb-6">
      <svg class="text-cyan-600 w-10 h-10" fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path>
      </svg>
      <h3 class="text-xl my-3 font-semibold font-heading">Lorem</h3>
      <p class="text-gray-400 leading-relaxed">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
    </div>
    <div class="lg:w-1/3 px-4 mb-6">
      <svg class="text-cyan-600 w-10 h-10" fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z"></path>
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z"></path>
      </svg>
      <h3 class="text-xl my-3 font-semibold font-heading">Ipsum</h3>
      <p class="text-gray-400 leading-relaxed">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</p>
    </div>
    <div class="lg:w-1/3 px-4 mb-6">
      <svg class="text-cyan-600 w-10 h-10" fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path>
      </svg>
      <h3 class="text-xl my-3 font-semibold font-heading">Dolor</h3>
      <p class="text-gray-400 leading-relaxed">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor</p>
    </div>
  </div>
</section>
<section class="py-12 px-4 text-center">
  <h2 class="text-4xl mb-8 font-semibold font-heading">Consectetur</h2>
  <div class="max-w-2xl mx-auto">
    <img class="rounded shadow" src="pictures/office.jpg" alt="">
    <div class="text-center mt-8 mb-6">
      <button class="inline-flex items-center justify-center h-3 w-3 mr-2 bg-gray-400 rounded-full"></button>
      <button class="inline-flex items-center justify-center h-3 w-3 mr-2 bg-gray-200 rounded-full"></button>
      <button class="inline-flex items-center justify-center h-3 w-3 mr-2 bg-gray-200 rounded-full"></button>
    </div>
    <div>
      <h3 class="text-2xl mb-4 font-semibold font-heading">Lorem ipsum</h3>
      <p class="text-gray-400 leading-relaxed">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
  </div>
</section>
<section class="py-8 px-4">
  <div class="flex flex-wrap -mx-8 text-center">
    <div class="w-full md:w-1/2 p-8 mb-4 md:mb-0">
      <h3 class="text-5xl font-semibold font-heading">$9 / mo</h3>
      <p class="flex-grow mt-4 mb-6 text-gray-400 leading-relaxed">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
      <a class="inline-block py-4 px-8 leading-none text-white bg-cyan-600 hover:bg-cyan-700 font-semibold rounded shadow" href="#">Contact sales</a>
    </div>
    <div class="w-full md:w-1/2 p-8 mb-4 md:mb-0 md:border-l">
      <h3 class="text-5xl font-semibold font-heading">$49 / mo</h3>
      <p class="mt-4 mb-6 text-gray-400 leading-relaxed">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
      <a class="inline-block py-4 px-8 leading-none text-cyan-600 bg-cyan-50 hover:bg-cyan-100 font-semibold rounded shadow" href="#">Contact sales</a>
    </div>
  </div>
</section>
<section class="py-12 px-4">
  <div class="flex flex-wrap -mx-4">
    <div class="lg:w-1/2 px-4 mb-4 lg:mb-0"><img class="rounded shadow" src="pictures/paper.jpg" alt=""></div>
    <div class="lg:w-1/2 px-4">
      <h2 class="text-4xl mb-4 font-semibold font-heading">Lorem ipsum dolor sit amet</h2>
      <p class="mb-6 text-gray-400 leading-relaxed">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      <div class="mb-6">
        <button class="inline-flex items-center justify-center h-8 w-8 mr-2 bg-gray-400 rounded-full"></button>
        <button class="inline-flex items-center justify-center h-8 w-8 mr-2 bg-gray-300 rounded-full"></button>
        <button class="inline-flex items-center justify-center h-8 w-8 mr-2 bg-gray-100 rounded-full"></button>
      </div>
      <div class="flex mb-6">
        <span class="text-2xl">$10</span>
        <div class="flex flex-wrap ml-4">
          <div class="w-1/2">
            <input class="appearance-none block w-full py-2 px-4 leading-snug text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded md:rounded-r-none focus:outline-none" type="number" value="1">
          </div>
          <div class="w-1/2">
            <button class="inline-block w-full py-3 px-4 leading-none text-white bg-cyan-600 hover:bg-cyan-700 font-semibold rounded md:rounded-l-none">Buy</button>
          </div>
        </div>
      </div>
      <div class="pt-4 border-t"><a class="text-cyan-600 hover:underline" href="#">Add to favorites</a></div>
    </div>
  </div>
</section>
<div class="flex p-4">
  <ul class="flex mx-auto list-reset border border-grey-light rounded">
    <li><a class="block px-3 py-2 text-cyan-600 hover:text-white hover:bg-cyan-700 border-r border-grey-light" href="#">Previous</a></li>
    <li><a class="block px-3 py-2 text-cyan-600 hover:text-white hover:bg-cyan-700 border-r border-grey-light" href="#">1</a></li>
    <li><a class="block px-3 py-2 text-cyan-600 hover:text-white hover:bg-cyan-700 border-r border-grey-light" href="#">2</a></li>
    <li><a class="block px-3 py-2 text-cyan-600 hover:text-white hover:bg-cyan-700 border-r border-grey-light" href="#">3</a></li>
    <li><a class="block px-3 py-2 text-cyan-600 hover:text-white hover:bg-cyan-700" href="#">Next</a></li>
  </ul>
</div>
<section class="py-12 px-4">
  <div class="flex flex-wrap -mx-4">
    <div class="w-full lg:w-1/2 px-4 mb-8 lg:mb-0">
      <div class="flex flex-col h-full p-8 bg-gray-100 rounded">
        <h2 class="text-3xl font-semibold font-heading">Lorem ipsum dolor sit amet</h2>
        <p class="max-w-sm mt-auto mb-8 text-gray-400 leading-relaxed">Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
        <a class="text-right text-cyan-600 hover:underline" href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit</a>
      </div>
    </div>
    <div class="lg:w-1/2 px-4">
      <div class="flex flex-wrap -m-2">
        <div class="w-1/2 p-2"><img class="rounded shadow" src="pictures/office.jpg" alt=""></div>
        <div class="w-1/2 p-2"><img class="rounded shadow" src="pictures/work.jpg" alt=""></div>
        <div class="w-1/2 p-2"><img class="rounded shadow" src="pictures/work.jpg" alt=""></div>
        <div class="w-1/2 p-2"><img class="rounded shadow" src="pictures/office.jpg" alt=""></div>
      </div>
    </div>
  </div>
</section>
<section class="pt-8 px-4 text-center">
  <div class="max-w-2xl mx-auto mb-8">
    <h2 class="text-4xl leading-tight mb-6 font-semibold font-heading">Lorem ipsum dolor sit amet</h2>
    <p class="text-gray-400 leading-relaxed">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class="flex flex-wrap -mx-8">
    <div class="w-1/2 md:w-1/6 px-8 mb-8"><img src="logos/realweb.svg" alt=""></div>
    <div class="w-1/2 md:w-1/6 px-8 mb-8"><img src="logos/gitscape.svg" alt=""></div>
    <div class="w-1/2 md:w-1/6 px-8 mb-8"><img src="logos/k-hole.svg" alt=""></div>
    <div class="w-1/2 md:w-1/6 px-8 mb-8"><img src="logos/plucky.svg" alt=""></div>
    <div class="w-1/2 md:w-1/6 px-8 mb-8"><img src="logos/1stsight.svg" alt=""></div>
    <div class="w-1/2 md:w-1/6 px-8 mb-8"><img src="logos/tholio.svg" alt=""></div>
  </div>
</section>
<section>
  <div>
    <ul>
      <li class="text-blue-100 bg-blue-800">blue 100</li>
      <li class="text-blue-300 bg-blue-800">blue 300</li>
      <li class="text-blue-500 bg-blue-800">blue 500</li>
      <li class="text-blue-700 bg-blue-800">blue 700</li>
      <li class="text-cyan-100 bg-cyan-800">cyan 100</li>
      <li class="text-cyan-300 bg-cyan-800">cyan 300</li>
      <li class="text-cyan-500 bg-cyan-800">cyan 500</li>
      <li class="text-cyan-700 bg-cyan-800">cyan 700</li>
      <li class="text-green-100 bg-green-800">green 100</li>
      <li class="text-green-300 bg-green-800">green 300</li>
      <li class="text-green-500 bg-green-800">green 500</li>
      <li class="text-green-700 bg-green-800">green 700</li>
      <li class="text-red-100 bg-red-800">red 100</li>
      <li class="text-red-300 bg-red-800">red 300</li>
      <li class="text-red-500 bg-red-800">red 500</li>
      <li class="text-red-700 bg-red-800">red 700</li>
      <li class="text-cyan-100 bg-cyan-800">cyan 100</li>
      <li class="text-cyan-300 bg-cyan-800">cyan 300</li>
      <li class="text-cyan-500 bg-cyan-800">cyan 500</li>
      <li class="text-cyan-700 bg-cyan-800">cyan 700</li>
      <li class="text-warmgray-100 bg-warmgray-800">warmgray 100</li>
      <li class="text-warmgray-300 bg-warmgray-800">warmgray 300</li>
      <li class="text-warmgray-500 bg-warmgray-800">warmgray 500</li>
      <li class="text-warmgray-700 bg-warmgray-800">warmgray 700</li>
      <li class="text-truegray-100 bg-truegray-800">truegray 100</li>
      <li class="text-truegray-300 bg-truegray-800">truegray 300</li>
      <li class="text-truegray-500 bg-truegray-800">truegray 500</li>
      <li class="text-truegray-700 bg-truegray-800">truegray 700</li>
      <li class="text-gray-100 bg-gray-800">gray 100</li>
      <li class="text-gray-300 bg-gray-800">gray 300</li>
      <li class="text-gray-500 bg-gray-800">gray 500</li>
      <li class="text-gray-700 bg-gray-800">gray 700</li>
    </ul>
  </div>
</section>

app/views/pages/index.html.erb
<%= content_for :page_title, 'Home Page' %>
<%= content_for :page_description, 'Home Page' %>
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/welcome.html.erb
<%= content_for :page_title, 'Welcome Page' %>
<%= content_for :page_description, 'Welcome Page' %>
<h1>Pages#welcome</h1>
<p>Find me in app/views/pages/welcome.html.erb</p>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="actions mb-5">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.published %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Published:</strong>
  <%= @post.published %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>